export const PAGE_NOT_FOUND = '**';
export const HOME = '';
export const FORGOT_PASSWORD = '/forgot-password';
export const RESET_PASSWORD = '/reset-password';
export const DASHBOARD = '/dashboard';
export const PARCELS = DASHBOARD + '/parcels';
export const EDIT_PARCEL = id => PARCELS + `/${id}/edit`;
export const CREATE_PARCEL = DASHBOARD + '/create-parcel';
export const PARCEL_DETAILS = PARCELS + '/:id';
export const ACCOUNT = DASHBOARD + '/account';
export const EDIT_ACCOUNT = ACCOUNT + '/edit';
export const CHANGE_PASSWORD = ACCOUNT + '/change-password';
export const UNAUTHENTICATED = '/unauthenticated';
